[programs.localnet]
nift_solana = "7jpnzC3ZyPCX93ymm4zq3ePV6YBJMPiBZueieUC8jnnt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ylgr/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
